fix(workflows): check.yml: use `nix flake show --json --legacy`

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -17,6 +17,11 @@ jobs:
       - uses: actions/checkout@v6.0.2
         with:
           submodules: 'true'
+      - name: Move to dotfiles directory
+        run: |
+          # checkout seems to put us in submodules git directory
+          # let's hard-code path to dotfiles directory for now
+          cd /home/runner/work/dotfiles/dotfiles/
       - name: Check Nix flake inputs
         uses: DeterminateSystems/flake-checker-action@v12
         with:
@@ -28,10 +33,11 @@ jobs:
           diagnostic-endpoint: ""
       - name: Inspect flake outputs
         run: |
-          echo "Available packages:"
-          nix flake show . --json 2>/dev/null | jq '.packages | ."x86_64-linux" | to_entries | map("\(.key) # \(.value.description)")'
-          echo "Available overlays:"
-          nix flake show . --json 2>/dev/null | jq '.overlays | to_entries | map(.key)'
-          echo "Available apps:"
-          nix flake show . --json 2>/dev/null | jq '.apps | ."x86_64-linux" | to_entries | map("\(.key)")'
+          flake="$(nix flake show . --json --legacy 2>/dev/null)"
+          
+          jq -r '
+              "Available packages:", ((.packages."x86_64-linux" // {}) | to_entries[] | "  \(.key) # \(.value.description)"),
+              "\nAvailable overlays:", (.overlays | keys[] | "  \(.)"),
+              "\nAvailable apps:", ((.apps."x86_64-linux" // {}) | keys[] | "  \(.)")
+          ' <<< "$flake" || { echo "Warning: could not parse flake output" ; jq <<< "$flake"; }
       - run: nix flake check
